name: e2e-tests-cucumber
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          env: true
          browser: chrome
        env: 
          ORANGE_USERNAME: ${{secrets.ORANGE_USERNAME}}
          ORANGE_PASSWORD: ${{secrets.ORANGE_PASSWORD}}
      - name: Generate report
        run: npm run generate:report
      - name: Deploy reports page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
